# FutureGateway fgapiserver component playbook 
#
# Author: Riccardo Bruno <riccardo.bruno@ct.infn.it>

- hosts: fgAPIServer
  remote_user: "{{ fg_connect_user }}" 
  become: yes
  become_method: sudo
  vars_files:
    - vars/fgdatabase.yml
    - vars/fgcommons.yml
    - vars/fgapiserver.yml
  tasks:
    # Package installation: sshpass, pdftk, xvfb, wkhtmltopdf 
    # yum is not yet supported unless for sshpass (no PDF on RedHat
    # bases systems will be available)
    - name: ReqPackages_yum | Install required packages for RedHat
      yum: name="{{ item }}" state=latest
      with_items:
         - sshpass 
      when: ansible_os_family == "RedHat"
    - name: ReqPackages_apt | Install required packages for Debian
      apt: pkg="{{ item }}" state=latest
      with_items:
         - pdftk 
         - xvfb
         - wkhtmltopdf  
         - sshpass 
      when: ansible_os_family == "Debian"
    # www directories
    - name: www_css | Creates fgtest/www/css directory
      file: path=/home/{{ fg_user }}/fgAPIServer/fgtest/www/css state=directory
    - name: www_js | Creates fgtest/www/js directory
      file: path=/home/{{ fg_user }}/fgAPIServer/fgtest/www/js state=directory
    # jquery
    - name: jquery | install jquery 
      command: wget https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js -O /home/{{ fg_user }}/fgAPIServer/fgtest/www/js/jquery.min.js 
               creates=/home/{{ fg_user }}/fgAPIServer/fgtest/www/js/jquery.min.js
    # bootstrap
    - name: bootstrap | get bootstrap 
      command: wget https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip -O /home/{{ fg_user }}/fgAPIServer/fgtest/bootstrap-3.3.7-dist.zip 
               creates="/home/{{ fg_user }}/fgAPIServer/fgtest/bootstrap-3.3.7-dist.zip"
    - name: bootstrap_unzip | Unzip bootstrap
      command: unzip bootstrap-3.3.7-dist.zip
               chdir=/home/{{ fg_user }}/fgAPIServer/fgtest
               creates=/home/{{ fg_user }}/fgAPIServer/fgtest/bootstrap-3.3.7-dist
    - name: bstheme | bootstrap-theme.min.css
      command: ln -s ../../bootstrap-3.3.7-dist/css/bootstrap-theme.min.css bootstrap-theme.min.css
               chdir=/home/{{ fg_user }}/fgAPIServer/fgtest/www/css
               creates=/home/{{ fg_user }}/fgAPIServer/fgtest/www/css/bootstrap-theme.min.css
    - name: bstheme.map | bootstrap-theme.min.css.map
      command: ln -s ../../bootstrap-3.3.7-dist/css/bootstrap-theme.min.css.map bootstrap-theme.min.css.map 
               chdir=/home/{{ fg_user }}/fgAPIServer/fgtest/www/css
               creates=/home/{{ fg_user }}/fgAPIServer/fgtest/www/css/bootstrap-theme.min.css.map
    - name: bstmin | bootstrap.min.css
      command: ln -s ../../bootstrap-3.3.7-dist/css/bootstrap.min.css bootstrap.min.css 
               chdir=/home/{{ fg_user }}/fgAPIServer/fgtest/www/css
               creates=/home/{{ fg_user }}/fgAPIServer/fgtest/www/css/bootstrap.min.css
    - name: bstmin.map | bootstrap.min.css.map
      command: ln -s ../../bootstrap-3.3.7-dist/css/bootstrap.min.css.map bootstrap.min.css.map 
               chdir=/home/{{ fg_user }}/fgAPIServer/fgtest/www/css
               creates=/home/{{ fg_user }}/fgAPIServer/fgtest/www/css/bootstrap.min.css
    - name: bsfonts | bootstrap fonts
      command: ln -s ../bootstrap-3.3.7-dist/fonts/ fonts 
               chdir=/home/{{ fg_user }}/fgAPIServer/fgtest/www
               creates=/home/{{ fg_user }}/fgAPIServer/fgtest/www/fonts
    - name: bsjs | bootstrap js
      command: ln -s ../../bootstrap-3.3.7-dist/js/bootstrap.min.js bootstrap.min.js    
               chdir=/home/{{ fg_user }}/fgAPIServer/fgtest/www/js
               creates=/home/{{ fg_user }}/fgAPIServer/fgtest/www/js/bootstrap.min.js
    # Configure apache to publish www dir
    - name: fgtest_www | Configure apache to publish fgtest/www directory 
      template:
        src: templates/fgtest_www.conf.j2
        dest: "/etc/apache2/sites-available/fgtest.conf"
        owner: root
        group: root
        mode: 0644
      register: fgtest_conf
    # Enable fgtest site
    - name: fgtest_enable | Enable fgtest site under fgtest/www
      command: ln -s /etc/apache2/sites-available/fgtest.conf /etc/apache2/sites-enabled/fgtest.conf
               creates=/etc/apache2/sites-enabled/fgtest.conf
    # Restart apache
    - name: restart_apache | Restart apahe web server
      service:
        name: apache2 
        state: restarted
      when: fgtest_conf.changed
    # Execute tesst
    - name: testexec | Execute tests
      raw: cd /home/{{ fg_user }}/fgAPIServer/fgtest ; ./fgtest.sh >fgtest.out 2>fgtest.err
           executable=/bin/bash
           chdir=/home/{{ fg_user }}/fgAPIServer/fgtest
           creates=/home/{{ fg_user }}/fgAPIServer/fgtest/www/index.html
