# FutureGateway apiserverdaemon configurable values are placed here
#
# Author: Riccardo Bruno <riccardo.bruno@ct.infn.it>

# APIServerDaemon application server:
# none - Does not setup any application server 
# tomcat - install and configure Apache Tomcat
# ... - Add your own PTV service installation
fg_appserver: 'tomcat'

# Tomcat values
tomcat_user: tomcat
tomcat_pass: t0mc@t_p@ssw0rd

# FutureGateway jobtester user
tester_user: jobtest
tester_pass: j0bt3st

# GridnCloudEngine UsersTrackingDB
ut_db_jndi: jdbc/UserTrackingPool
ut_db_host: "{{ host_ut_db_host }}"
ut_db_port: "{{ mysql_port }}" 
ut_db_user: tracking_user
ut_db_password: usertracking
ut_db_name: userstracking

# APIServerDaemon JSAGA adaptors
fg_rOCCI_adaptor_git: 'https://github.com/csgf/jsaga-adaptor-rocci.git'
fg_rOCCI_adaptor_gitver: 'master'
fg_GridnCloudEngine_git: 'https://github.com/csgf/grid-and-cloud-engine.git'
fg_GridnCloudEngine_gitver: 'FutureGateway'

# VOMS Settings: vo.indigo-datacloud.eu
voms_indigo_lsc: |
                 /C=PT/O=LIPCA/O=LIP/OU=Lisboa/CN=voms01.ncg.ingrid.pt
                 /C=PT/O=LIPCA/CN=LIP Certification Authority
voms_indigo_vomses: |
                    "vo.indigo-datacloud.eu" "voms01.ncg.ingrid.pt" "40101" "/C=PT/O=LIPCA/O=LIP/OU=Lisboa/CN=voms01.ncg.ingrid.pt" "vo.indigo-datacloud.eu"

#
# APIServerDaemon .properties files
#

# Log4j config file
asd_file_appender: org.apache.log4j.RollingFileAppender
asd_file_file: ${APISrvDaemonPath}WEB-INF/logs/APIServerDaemon.log
asd_file_maxfilesize: 100MB
asd_file_maxbackupindex: 10
asd_file_layout: org.apache.log4j.PatternLayout
file_layout_conversionpattern: '%d{yyyy-MM-dd HH:mm:ss} %-5p %t %c{1}:%L - %m%n'

# APIServerDaemon.properties
asdMaxThreads: 100
asdCloseTimeout: 20
gePollingDelay: 4000
gePollingMaxCommands: 5
asControllerDelay: 10000
asControllerMaxCommands: 5
asTaskMaxRetries: 5
asTaskMaxWait: 1800000
utdb_jndi: "{{ ut_db_jndi }}" 
utdb_host: "{{ ut_db_host }}"
utdb_port: "{{ ut_db_port }}"
utdb_user: "{{ ut_db_user }}"
utdb_pass: "{{ ut_db_password }}"
utdb_name: "{{ ut_db_name }}"

# ToscaIDC.properties
fgapisrv_ptvendpoint: http://localhost:8889
fgapisrv_ptvuser: tokenver_user
fgapisrv_ptvpass: tokenver_pass

# APIServerDaemon environment file
fg_apiserverdaemon: |
                    #!/bin/bash
                    #
                    # APIServerDaemon Environment settings configuration file
                    #
                    # Very specific APIServerDaemon service component environment must be set here
                    #
                    # Author: Riccardo Bruno <riccardo.bruno@ct.infn.it>

                    catalina_env() {
                      export CATALINA=$(locate catalina.sh)
                      export CATALINA_HOME=$($CATALINA version | grep CATALINA_HOME| awk -F":" '{ print $2 }' | xargs echo )
                      export CATALINA_BASE=$($CATALINA version | grep CATALINA_BASE | awk -F":" '{ print $2 }' | xargs echo )
                    }

                    # Set CATALINA variables
                    catalina_env

                    export UTDB_HOST="{{ ut_db_host }}"
                    export UTDB_PORT="{{ ut_db_port }}"
                    export UTDB_USER="{{ ut_db_user }}"
                    export UTDB_PASSWD="{{ ut_db_password }}"
                    export UTDB_NAME="{{ ut_db_name }}"
                    export UTDB_OPTS=''
                    export UTDB_ROOTPWD="{{ mysql_root_password }}"

# Testing JSAGA with SSH connection
test_ssh_host: "{{ jsaga_ssh_host }}"
test_ssh_port: "{{ jsaga_ssh_port }}"
